# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'my website'


# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Game', url: 'game'}
- {name: 'Tool', url: 'tool'}
- {name: 'About', url: 'about'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'envelope', link:   'maierelias13@gmail.com'}
- {icon: 'github',     link: 'https://github.com/eeli1'}
- {icon: 'linkedin',   link: 'https://www.linkedin.com/in/elias-maier-4b8b75219/'}
# - {icon: 'rss-square', link: 'feed.xml'}

# Customize site text
pagination:
  next_page: 'next'
  previous_page: 'previous'


# sharing_button_prompt: 'Feel free to share!'

# related_posts: 'You may also enjoy...'

# post_date_prefix: 'Written on'
